apiVersion: v1
kind: ConfigMap
metadata:
  name: sinpeconectacr-config
  namespace: sinpeconectacr
data:
  POSTGRES_DB: "sinpeconectacr"
  POSTGRES_USER: "sinpeconectacr"
  POSTGRES_PASSWORD: "sinpeconectacr"

  DATABASE_URL: "postgresql://sinpeconectacr:sinpeconectacr@postgres:5432/sinpeconectacr"
  REDIS_URL: "redis://redis:6379"
  NATS_URL: "nats://nats:4222"

  VITE_API_URL: "http://sinpeconectacr.local:8080"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PAYMENTS_SERVICE_URL: "http://payments-service:3002"
  CRM_SERVICE_URL: "http://crm-service:3003"
  IA_SERVICE_URL: "http://ia-service:3004"

  JWT_SECRET: "dev_secret_change_me"
