apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sinpeconectacr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: dorianprogrammer/api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: sinpeconectacr-config
                  key: AUTH_SERVICE_URL
            - name: PAYMENTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: sinpeconectacr-config
                  key: PAYMENTS_SERVICE_URL
            - name: CRM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: sinpeconectacr-config
                  key: CRM_SERVICE_URL
            - name: IA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: sinpeconectacr-config
                  key: IA_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sinpeconectacr
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000